name: DigitalOcean Container Registry Remove
description: Remove old image tags from Digital Ocean's Container Registry
branding:
  icon: 'trash'
  color: 'blue'

inputs:
  image_repository:
    description: Image repository name in the Container Registry
    required: true
  buffer_size:
    description: Number of recent images. Default is 10
    required: false
    default: 10
  exclude:
    description: Tag regex to exclude. Example - ^(latest|tag1|tag2)$
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Remove images older than the last n versions
      shell: bash
      run: ${{ github.action_path }}/remove_images.sh ${{ inputs.image_repository }} ${{ inputs.buffer_size }} '${{ inputs.exclude }}'
